Say
egorka193/learnico-html-css pull request #4
Opened 2024-10-09 14:02 UTC by egorka193

2024-10-10 07:27 UTC, Platon79 commented on index.html
> +  <div class="say">
вертикальный скролл видно
![Снимок экрана 2024-10-10 в 09 26 00](https://github.com/user-attachments/assets/f061df70-9c48-4dbf-bcd6-a32cf18edb60)

2024-10-10 07:28 UTC, Platon79 commented on style.css
> +  position: absolute;
тоже самое было в блоке about, но мы сделали по-другому. Так почему тут ты опять делаешь абсолютное позиционирование?

2024-10-10 07:30 UTC, Platon79 commented on style.css
> +  background-color: white;
тут нужно добавить `display: inline-block;`

2024-10-10 07:34 UTC, Platon79 commented on style.css
> +.say__container{
сюда также стоит добавить свойство `overflow: hodden;`, чтобы скролл не выходил за рамки блока
![image](https://github.com/user-attachments/assets/a375ff6c-609b-494e-81d5-44570df0775b)

2024-10-10 07:36 UTC, Platon79 commented on style.css
> +.say__container{
либо стоит сделать двойной паддинг, чтобы было так
![image](https://github.com/user-attachments/assets/2d7d7e1e-399b-4ba0-8b2c-0fa7426946d9)

2024-10-10 07:38 UTC, Platon79 commented on index.html
> +            <div class="say__card-photo">
у этого блока должна быть зафиксирована ширина. Сейчас все фотки выглядят одинаково, только потому что исходные картинки одного размера. В реальной жизни они могут иметь большее качество и сразу разъедутся

2024-10-10 07:40 UTC, Platon79 commented on style.css
> +.say__card p{
лучше не делай такой селектор, а дай тэгу `р` отдельный класс. Сейчас у тебя этот стиль также начинает влиять на тэг `р` с классом `say__card-prof`

2024-10-10 07:43 UTC, Platon79 commented on style.css
> +  border-radius: 3px;
радиус отличается от дизайна

2024-10-10 07:44 UTC, Platon79 commented on index.html
> +            <a class="post__card-link1">Freelance</a>
это не ссылка. Это просто лейбл. Нужно использовать другой тэг

2024-10-10 07:45 UTC, Platon79 commented on index.html
> +      <p class="posts__text">Blog</p>
это не параграф. Тут всего одно слово. Используй другой тэг

2024-10-10 07:46 UTC, Platon79 commented on style.css
> +  max-width: 45px;
не надо тут использовать ширину. Нужно чтобы кнопка занимала столько места, сколько требует ее контент

2024-10-10 07:54 UTC, Platon79 commented on index.html
> +      <div class="posts__latest">
posts__latest плохое название. Ты просто взял слово из названия и использовал его для имени. Так не годится. Надо называть по смыслу.
Например в данном случае можно было использовать posts__head или posts__top

2024-10-10 07:56 UTC, Platon79 commented on style.css
> +  width: 405px;
лучше не использовать пиксели в данном случае. Ширина контейнера может измениться, тогда тебе придется пересчитывать и эту ширину. Используй проценты

2024-10-10 07:59 UTC, Platon79 commented on style.css
> +.post__card-link1 {
я уже говорил, что нельзя использовать индексы в названиях классов

2024-10-10 08:00 UTC, Platon79 commented on style.css
> +.post__card-link1 {
это относится ко многим местам в этом блоке. Исправь все

2024-10-10 08:01 UTC, Platon79 commented on style.css
> +  margin-bottom: 37px;
избавься полностью от margin-bottom для этих текстов. Используй flexbox, чтобы разместить ссылку внизу

2024-10-10 08:03 UTC, Platon79 commented on style.css
> +.say {
переименуй блоки say.
say переводится как  "говорить". В этом нет никакого смысла.

2024-10-10 08:04 UTC, Platon79 commented on style.css
> +.today {
сделай класс `start-today`, вместо просто `today`

2024-10-10 08:04 UTC, Platon79 requested changes
Почини комменты, которые я оставил в коде

2024-10-10 09:28 UTC, egorka193 commented on index.html
> +  <div class="say">
fixed

2024-10-10 09:37 UTC, egorka193 commented on index.html
> +            <div class="say__card-photo">
fixed

2024-10-10 09:42 UTC, egorka193 commented on style.css
> +.say__card p{
fixed

2024-10-10 09:42 UTC, egorka193 commented on style.css
> +  background-color: white;
fixed

2024-10-10 09:45 UTC, egorka193 commented on style.css
> +  border-radius: 3px;
fixed

2024-10-10 09:49 UTC, egorka193 commented on index.html
> +            <a class="post__card-link1">Freelance</a>
fixed

2024-10-10 10:14 UTC, egorka193 commented on style.css
> +  max-width: 45px;
fixed

2024-10-10 10:15 UTC, egorka193 commented on index.html
> +      <p class="posts__text">Blog</p>
fixed

2024-10-10 10:17 UTC, egorka193 commented on index.html
> +      <div class="posts__latest">
fixed

2024-10-10 11:19 UTC, egorka193 commented on style.css
> +  width: 405px;
fixed

2024-10-10 11:21 UTC, egorka193 commented on style.css
> +.post__card-link1 {
fixed

2024-10-10 13:23 UTC, egorka193 commented on style.css
> +  margin-bottom: 37px;
fixed

2024-10-10 13:37 UTC, egorka193 commented on style.css
> +.say {
fixed

2024-10-10 13:56 UTC, egorka193 commented on style.css
> +  position: absolute;
fixed

2024-10-10 14:30 UTC, Platon79 commented on index.html
> +            <div class="say__card-photo">
недостаточно дать ширину блоку, нужно, чтобы ширина работала с картинкой

2024-10-10 14:33 UTC, Platon79 commented on index.html
> +            <a class="post__card-link1">Freelance</a>
имя все еще неверное. Избавься от индексов

2024-10-11 07:36 UTC, Platon79 approved these changes

2024-10-11 07:38 UTC, merged